services:
  db:
    image: postgres:15
    container_name: banco_db
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banco"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./banco-api
    container_name: banco_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./banco-frontend
    container_name: banco_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend